openapi: "3.0.1"
info:
  title: PoC Hexagonal Architecture
  description: API de sevicios, para implementar la prueba de concepto solicitada
  contact:
    name: Óscar Andújar Hinarejos
    email: oandujar@minsait.com
  version: 1.0.0
paths:
  /price/brand/{brandId}/product/{productId}:
    get:
      summary: Servicio que permite obtener la información de un producto y marca.
      operationId: getProductPrice
      tags:
        - Products
      parameters:
        - name: brandId
          in: path
          description: Id de la marca.
          required: true
          schema:
            type: integer
            format: int64
        - name: productId
          in: path
          description: Id del producto.
          required: true
          schema:
            type: integer
            format: int64
        - name: date
          in: query
          description: Fecha de aplicación de la tarifa.
          required: false
          example: 1993-09-16T14:30:00.00Z
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: Información del producto y marca relacionada con la tarifa a aplicar, fechas de aplicación y precio final.
          content:
            application/json:
              schema:
                type:
                  array
                items:
                  $ref: '#/components/schemas/ProductPriceResponse'
        400:
          description: Petición mal formada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: No se permite realizar esa acción, permiso denegado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: Acceso prohibido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: No encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        409:
          description: Error al ejecutar la petición
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ProductPriceResponse:
      title: ProductResponse
      type: object
      properties:
        productId:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        brandId:
          type: integer
          format: int32
        brand:
          type: string
        fee:
          type: integer
          format: int32
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: string
        currency:
          type: string
        priority:
          type: integer
          format: int32
