-- liquibase formatted sql

-- changeset oandujar:1697700859929-1
CREATE TABLE brand
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_brand PRIMARY KEY (id)
);

-- changeset oandujar:1697700859929-2
CREATE TABLE prices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand_id   BIGINT,
    start_date TIMESTAMP with time zone,
    end_date   TIMESTAMP with time zone,
    price_list BIGINT,
    product_id BIGINT,
    price      DOUBLE PRECISION,
    currency   VARCHAR(255),
    priority   BIGINT,
    CONSTRAINT pk_prices PRIMARY KEY (id)
);

-- changeset oandujar:1697700859929-3
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- changeset oandujar:1697700859929-4
ALTER TABLE prices
    ADD CONSTRAINT FK_PRICES_ON_BRAND FOREIGN KEY (brand_id) REFERENCES brand (id);

-- changeset oandujar:1697700859929-5
ALTER TABLE prices
    ADD CONSTRAINT FK_PRICES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

